# Generated by Django 5.2 on 2025-04-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('income', models.FloatField()),
                ('expenses', models.FloatField()),
                ('emi', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('loan_term', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
