# Generated by Django 5.2 on 2025-05-14 08:54

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': 'Investment', 'verbose_name_plural': 'Investments'},
        ),
        migrations.AlterModelOptions(
            name='loanapplication',
            options={'verbose_name': 'Loan Application', 'verbose_name_plural': 'Loan Applications'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='predicted_loan_approval',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='predicted_loan_term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_type',
            field=models.CharField(choices=[('SIP', 'SIP'), ('Mutual Funds', 'Mutual Funds'), ('Stocks', 'Stocks'), ('Fixed Deposit', 'Fixed Deposit'), ('Gold', 'Gold'), ('Crypto', 'Crypto')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='emi',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='expenses',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='profile',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
